apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    release: "stable"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/akashnarayanan/Documents/rotc/ROTC-semi-guided-material/final_assignment/deployment-self/data"
    #path: "/var/root/data"
